networks:
  d_network:
    driver: bridge

volumes:
  site:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/src

services:
  app:
    container_name: d_app
    image: d_app
    build:
      dockerfile: Dockerfile
      context: .docker/php/
    restart: always
    networks:
      - d_network
    volumes:
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - site:/var/www/html

  db:
    container_name: d_db
    image: postgres:13.1
    restart: unless-stopped
    networks:
      - d_network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: d_db
    volumes:
      - ./.docker/database:/var/lib/postgresql/data
      - ./.docker/backups:/var/backups
    ports:
      - '5433:5432'

  server:
    container_name: d_server
    image: d_server
    build:
      context: .docker/nginx/
      dockerfile: Dockerfile
    networks:
      - d_network
    volumes:
      - site:/var/www/html
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/certs/server.crt:/etc/nginx/certs/cert.crt
      - ./.docker/nginx/certs/server.key:/etc/nginx/certs/cert.key
      - ./.docker/nginx/logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443

  workspace:
    container_name: d_workspace
    image: d_workspace
    build:
      context: .
      dockerfile: .docker/workspace/Dockerfile
    networks:
      - d_network
    volumes:
      - site:/var/www/html
    tty: true

  memcached:
    container_name: d_memcached
    image: memcached:latest
    restart: always
    networks:
      - d_network
    ports:
      - "11211:11211"
