<?php
    use \Drupal\Core\Url;
    function article_theme(){
        return [
            'blogs'=>[
                'template' => 'blogs/list',
                'variables'=> [
                    'data' => [],
                ]
            ],
            'manage_home' => [
                'template' => 'home_page',
                'variables' => [
                    'articles' => [],
                ],
            ],
            'manage_list' => [
                'template' => 'list_article',
                'variables' => [
                    'articles' => [],
                ],
            ],
            'manage_detail' => [
                'template' => 'detail-article',
                'variables' => [
                    'article' => [],
                ],
            ],
            'manage_search' => [
                'template' => 'search_results',
                'variables' => [
                    'articles' => [],
                ],
            ],
            'manage_tag' => [
                'template' => 'tag_article',
                'variables' => [
                    'articles' => [],
                ],
            ],
            'manage_contact' => [
                'template' => 'contact',
                'variables' => [
                    'data' => [],
                ],
            ],
        ];
    }
    function manage_toolbar(){
        $patterns = ['manage' => 'manage.load'];
        $module_handler = \Drupal::moduleHandler();
        // Build a list of links for the menu.
        $links = [];
        foreach ($patterns as $module => $route) {
            // Get the module info (title, description) from Drupal.
            $extension_list_module = \Drupal::service('extension.list.module');
            $info = $extension_list_module->getExtensionInfo($module);
            // If there's no info, the example isn't enabled, so don't display it.
            if (!empty($info)) {
                $links[$module] = array(
                    'title' => ($info['name']),
                    'url' => Url::fromRoute($route),
                    'attributes' => array(
                        'title' => $info['name'],
                    ),
                );
            }
        }
        $items['manage'] = [
            '#type'   => 'toolbar_item',
            'tab'     => [
                '#type'       => 'link',
                '#title'      => t('Custom menu'),
                '#url'        => Url::fromRoute('manage.load'),
                '#attributes' => [
                    'title' => t('Custom articles'),
                    'class' => [
                        'toolbar-icon',
                        'toolbar-icon-menu'
                    ],
                ],
            ],
            'tray' => array(
                '#heading' => t('Toppage Management'),
                'shortcuts' => array(
                    '#theme' => 'links__toolbar_patterns',
                    '#links' => $links,
                    '#attributes' => array(
                        'class' => array('toolbar-menu'),
                    ),
                ),
            ),
        ];

        return $items;
    }
